#
# Client for HP P1218A TopTools Remote Control
#
# Copyright (c) 2011-2012 Pascal Terjan <pterjan@gmail.com>
#               All Rights Reserved
#
# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# http://sam.zoy.org/wtfpl/COPYING for more details.

require 'gtk2'

module Keyboard
# Scancodes for Set 1
# Based on http://www.quadibloc.com/comp/scan.htm
SCANCODES = {
 "0" => [ "b" ],
 "1" => [ "2" ],
 "2" => [ "3" ],
 "3" => [ "4" ],
 "4" => [ "5" ],
 "5" => [ "6" ],
 "6" => [ "7" ],
 "7" => [ "8" ],
 "8" => [ "9" ],
 "9" => [ "a" ],
 "A" => [ "2a", "1e" ],
 "B" => [ "2a", "30" ],
 "BackSpace" => [ "e" ],
 "C" => [ "2a", "2e" ],
 "Caps_Lock" => [ "3a" ],
 "D" => [ "2a", "20" ],
 "Delete" => [ "e0", "53" ],
 "Down" => [ "e0", "50" ],
 "E" => [ "2a", "12" ],
 "End" => [ "e0", "4f" ],
 "Escape" => [ "1" ],
 "F" => [ "2a", "21" ],
 "F1" => [ "3b" ],
 "F10" => [ "44" ],
 "F11" => [ "57" ],
 "F12" => [ "58" ],
 "F2" => [ "3c" ],
 "F3" => [ "3d" ],
 "F4" => [ "3e" ],
 "F5" => [ "3f" ],
 "F6" => [ "40" ],
 "F7" => [ "41" ],
 "F8" => [ "42" ],
 "F9" => [ "43" ],
 "G" => [ "2a", "22" ],
 "H" => [ "2a", "23" ],
 "Home" => [ "e0", "47" ],
 "I" => [ "2a", "17" ],
 "Insert" => [ "e0", "52" ],
 "J" => [ "2a", "24" ],
 "K" => [ "2a", "25" ],
 "KP_0" => [ "52" ],
 "KP_1" => [ "4f" ],
 "KP_2" => [ "50" ],
 "KP_3" => [ "51" ],
 "KP_4" => [ "4b" ],
 "KP_5" => [ "4c" ],
 "KP_6" => [ "4d" ],
 "KP_7" => [ "47" ],
 "KP_8" => [ "48" ],
 "KP_9" => [ "49" ],
 "KP_Add" => [ "4e" ],
 "KP_Decimal" => [ "53" ],
 "KP_Divide" => [ "e0", "35" ],
 "KP_Multiply" => [ "37" ],
 "KP_Subtract" => [ "4a" ],
 "L" => [ "2a", "26" ],
 "Left" => [ "e0", "4b" ],
 "M" => [ "2a", "32" ],
 "N" => [ "2a", "31" ],
 "Num_Lock" => [ "45" ],
 "O" => [ "2a", "18" ],
 "P" => [ "2a", "19" ],
 "Page_Down" => [ "e0", "51" ],
 "Page_Up" => [ "e0", "49" ],
 "Q" => [ "2a", "10" ],
 "R" => [ "2a", "13" ],
 "Return" => [ "1c" ],
 "Right" => [ "e0", "4d" ],
 "S" => [ "2a", "1f" ],
 "Scroll_Lock" => [ "46" ],
 "T" => [ "2a", "14" ],
 "Tab" => [ "f" ],
 "U" => [ "2a", "16" ],
 "Up" => [ "e0", "48" ],
 "V" => [ "2a", "2f" ],
 "W" => [ "2a", "11" ],
 "X" => [ "2a", "2d" ],
 "Y" => [ "2a", "15" ],
 "Z" => [ "2a", "2c" ],
 "a" => [ "1e" ],
 "ampersand" => [ "2a", "8" ],
 "apostrophe" => [ "28" ],
 "asciicircum" => [ "2a", "7" ],
 "asciitilde" => [ "2a", "29" ],
 "asterisk" => [ "2a", "9" ],
 "at" => [ "2a", "3" ],
 "b" => [ "30" ],
 "backslash" => [ "2b" ],
 "bar" => [ "2a", "2b" ],
 "braceleft" => [ "2a", "1a" ],
 "braceright" => [ "2a", "1b" ],
 "bracketleft" => [ "1a" ],
 "bracketright" => [ "1b" ],
 "c" => [ "2e" ],
 "colon" => [ "2a", "27" ],
 "comma" => [ "33" ],
 "d" => [ "20" ],
 "dollar" => [ "2a", "5" ],
 "e" => [ "12" ],
 "equal" => [ "d" ],
 "exclam" => [ "2a", "2" ],
 "f" => [ "21" ],
 "g" => [ "22" ],
 "grave" => [ "29" ],
 "greater" => [ "2a", "34" ],
 "h" => [ "23" ],
 "i" => [ "17" ],
 "j" => [ "24" ],
 "k" => [ "25" ],
 "l" => [ "26" ],
 "less" => [ "2a", "33" ],
 "m" => [ "32" ],
 "minus" => [ "c" ],
 "n" => [ "31" ],
 "numbersign" => [ "2a", "4" ],
 "o" => [ "18" ],
 "p" => [ "19" ],
 "parenleft" => [ "2a", "a" ],
 "parenright" => [ "2a", "b" ],
 "percent" => [ "2a", "6" ],
 "period" => [ "34" ],
 "plus" => [ "2a", "d" ],
 "q" => [ "10" ],
 "question" => [ "2a", "35" ],
 "quotedbl" => [ "2a", "28" ],
 "r" => [ "13" ],
 "s" => [ "1f" ],
 "semicolon" => [ "27" ],
 "slash" => [ "35" ],
 "space" => [ "39" ],
 "t" => [ "14" ],
 "u" => [ "16" ],
 "underscore" => [ "2a", "c" ],
 "v" => [ "2f" ],
 "w" => [ "11" ],
 "x" => [ "2d" ],
 "y" => [ "15" ],
 "z" => [ "2c" ],
}

def gdk_keyval_to_scancodes(k)
	return SCANCODES[Gdk::Keyval::to_name(k)] || []
end

end

